# AI Writer & Lorem Ipsum CKEditor plugins
# Import this in your RTE preset and add 'AiText', 'AiTranslate', and/or 'LoremIpsum' to toolbar items
editor:
  externalPlugins:
    ai_text:
      resource: 'EXT:ok_ai_writer/Resources/Public/CKEditor/Plugins/AiText/plugin.js'
    ai_translate:
      resource: 'EXT:ok_ai_writer/Resources/Public/CKEditor/Plugins/AiTranslate/plugin.js'
    lorem_ipsum:
      resource: 'EXT:ok_ai_writer/Resources/Public/CKEditor/Plugins/LoremIpsum/plugin.js'
