# AI Writer RTE preset
# Extends bootstrap_package RTE with AI Writer toolbar buttons
imports:
    - { resource: "EXT:bootstrap_package/Configuration/RTE/Default.yaml" }

editor:
  externalPlugins:
    ai_text:
      resource: 'EXT:ok_ai_writer/Resources/Public/CKEditor/Plugins/AiText/plugin.js'
    ai_translate:
      resource: 'EXT:ok_ai_writer/Resources/Public/CKEditor/Plugins/AiTranslate/plugin.js'
    lorem_ipsum:
      resource: 'EXT:ok_ai_writer/Resources/Public/CKEditor/Plugins/LoremIpsum/plugin.js'

  config:
    toolbarGroups:
      - { name: styles, groups: [ format, styles ] }
      - { name: basicstyles, groups: [ basicstyles ] }
      - { name: paragraph, groups: [ list, indent, blocks, align ] }
      - "/"
      - { name: links, groups: [ links ] }
      - { name: clipboard, groups: [ clipboard, cleanup, undo ] }
      - { name: editing, groups: [ spellchecker ] }
      - { name: insert, groups: [ insert ] }
      - { name: tools, groups: [ table, specialchar ] }
      - { name: ai, groups: [ ai ] }
      - { name: document, groups: [ mode ] }
